// Intake wizard: a local web page that collects what a company needs for its
// MCP server, writes a manifest.yaml, validates it with the real validator and
// can run the generator. Listens on 127.0.0.1 only; writes only under outRoot.

import http from "node:http";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { validateManifest, summarize, catalog } from "../../scripts/validate-manifest.mjs";
import { generate, ManifestError } from "../generator/generate.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "../..");
const MAX_BODY = 2 * 1024 * 1024;
const SERVER_NAME = /^[a-z0-9][a-z0-9-]*$/;

// Resource files uploaded in the wizard: { "docs/return-policy.md": "text" }.
// Paths must stay inside the manifest folder.
function safeFiles(files) {
  const out = [];
  for (const [rel, content] of Object.entries(files ?? {})) {
    const norm = path.posix.normalize(String(rel).replaceAll("\\", "/"));
    if (!norm || norm.startsWith("..") || path.posix.isAbsolute(norm) || typeof content !== "string") {
      throw new Error(`file "${rel}" must be a relative path inside the manifest folder`);
    }
    out.push([norm, content]);
  }
  return out;
}

export function writeWorkspace(dir, manifest, files) {
  mkdirSync(dir, { recursive: true });
  for (const [rel, content] of safeFiles(files)) {
    const dest = path.join(dir, rel);
    mkdirSync(path.dirname(dest), { recursive: true });
    writeFileSync(dest, content);
  }
  const yamlText = toYaml(manifest);
  const file = path.join(dir, "manifest.yaml");
  writeFileSync(file, yamlText);
  return { file, yamlText };
}

export function toYaml(manifest) {
  const header = `# Generated by the MCP Server Builder intake wizard.\n# Secrets are never written here: each *Env field names an environment variable.\n\n`;
  return header + YAML.stringify(manifest, { lineWidth: 0 });
}

// Validates in a throwaway folder so file resources are checked too.
export function check(manifest, files) {
  const tmp = mkdtempSync(path.join(os.tmpdir(), "mcpb-intake-"));
  try {
    const { file, yamlText } = writeWorkspace(tmp, manifest, files);
    const errors = validateManifest(YAML.parse(readFileSync(file, "utf8")), { baseDir: tmp });
    return { yaml: yamlText, errors, summary: errors.length ? null : summarize(manifest) };
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function projectDir(outRoot, manifest) {
  const name = manifest?.server?.name;
  if (typeof name !== "string" || !SERVER_NAME.test(name)) throw new Error("server.name must be set (kebab-case) before saving");
  return path.join(outRoot, name);
}

export function save(outRoot, manifest, files) {
  const result = check(manifest, files);
  if (result.errors.length) return { ...result, saved: false };
  const dir = projectDir(outRoot, manifest);
  const { file } = writeWorkspace(dir, manifest, files);
  return { ...result, saved: true, manifestPath: file };
}

export function runGenerate(outRoot, manifest, files) {
  const saved = save(outRoot, manifest, files);
  if (!saved.saved) return saved;
  const outDir = path.join(path.dirname(saved.manifestPath), "server");
  try {
    const r = generate(saved.manifestPath, outDir);
    const transports = r.config.server.transports;
    return {
      ...saved,
      generated: true,
      outDir,
      counts: { tools: r.tools.length, resources: r.resources.length, prompts: r.prompts.length },
      warnings: r.warnings,
      command: `node ${path.join(root, "src/cli/mcp-builder.mjs")} generate ${saved.manifestPath} --out ${outDir}`,
      nextSteps: [
        `cd ${outDir}`,
        "npm install",
        "npm run build",
        "cp .env.example .env   (then fill in the values)",
        transports.includes("http") ? "npm run start:stdio   or   npm run start:http" : "npm run start:stdio",
      ],
    };
  } catch (err) {
    return { ...saved, generated: false, generateError: err instanceof ManifestError ? err.message : err.message };
  }
}

function readJson(req) {
  return new Promise((resolve, reject) => {
    let size = 0;
    const chunks = [];
    req.on("data", (c) => {
      size += c.length;
      if (size > MAX_BODY) { reject(new Error("request too large")); req.destroy(); return; }
      chunks.push(c);
    });
    req.on("end", () => { try { resolve(JSON.parse(Buffer.concat(chunks).toString("utf8") || "{}")); } catch { reject(new Error("invalid JSON")); } });
    req.on("error", reject);
  });
}

function send(res, status, body, type = "application/json; charset=utf-8") {
  res.writeHead(status, { "content-type": type, "cache-control": "no-store", "x-content-type-options": "nosniff" });
  res.end(typeof body === "string" ? body : JSON.stringify(body));
}

const STATIC = {
  "/wizard.js": [path.join(root, "src/ui/wizard.js"), "text/javascript; charset=utf-8"],
  "/wizard.css": [path.join(root, "src/ui/wizard.css"), "text/css; charset=utf-8"],
  "/intake.js": [path.join(here, "intake.js"), "text/javascript; charset=utf-8"],
};

export function createIntakeServer({ outRoot }) {
  const page = () => readFileSync(path.join(here, "index.html"), "utf8");
  return http.createServer(async (req, res) => {
    const url = new URL(req.url, "http://localhost");
    try {
      // Only same-origin browser calls: blocks other sites from driving the local API.
      if (req.method === "POST") {
        const origin = req.headers.origin;
        if (origin && origin !== `http://${req.headers.host}`) return send(res, 403, { error: "cross-origin request refused" });
      }
      if (req.method === "GET" && url.pathname === "/") return send(res, 200, page(), "text/html; charset=utf-8");
      if (req.method === "GET" && STATIC[url.pathname]) {
        const [file, type] = STATIC[url.pathname];
        return send(res, 200, readFileSync(file, "utf8"), type);
      }
      if (req.method === "GET" && url.pathname === "/api/catalog") return send(res, 200, catalog);
      if (req.method === "GET" && url.pathname === "/api/example") {
        const name = url.searchParams.get("name") === "azure" ? "acme-outdoor-azure.yaml" : "acme-outdoor.yaml";
        const manifest = YAML.parse(readFileSync(path.join(root, "examples", name), "utf8"));
        const files = { "docs/return-policy.md": readFileSync(path.join(root, "examples/docs/return-policy.md"), "utf8") };
        return send(res, 200, { manifest, files });
      }
      if (req.method === "POST" && url.pathname === "/api/parse") {
        const { yaml } = await readJson(req);
        return send(res, 200, { manifest: YAML.parse(String(yaml ?? "")) ?? {} });
      }
      if (req.method === "POST" && ["/api/validate", "/api/save", "/api/generate"].includes(url.pathname)) {
        const { manifest, files } = await readJson(req);
        if (!manifest || typeof manifest !== "object") return send(res, 400, { error: "manifest missing" });
        const fn = { "/api/validate": () => check(manifest, files), "/api/save": () => save(outRoot, manifest, files), "/api/generate": () => runGenerate(outRoot, manifest, files) }[url.pathname];
        return send(res, 200, fn());
      }
      return send(res, 404, { error: "not found" });
    } catch (err) {
      return send(res, 400, { error: err.message });
    }
  });
}

export function startIntake({ port = 4321, outRoot = path.resolve("intake-output") } = {}) {
  const server = createIntakeServer({ outRoot: path.resolve(outRoot) });
  return new Promise((resolve) => server.listen(port, "127.0.0.1", () => resolve(server)));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  const flag = (n) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : undefined; };
  const server = await startIntake({ port: Number(flag("--port") ?? 4321), outRoot: flag("--out-root") ?? "intake-output" });
  console.log(`Intake wizard running at http://127.0.0.1:${server.address().port}/  (Ctrl+C to stop)`);
}

