// Turns a validated manifest into a TypeScript MCP server project.
// The generated project = small per-item files (tools, resources, prompts,
// config) + a shared runtime copied from templates/server-ts.

import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { fileURLToPath } from "node:url";
import YAML from "yaml";
import { validateManifest, allTools, catalog } from "../../scripts/validate-manifest.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const templateDir = path.join(root, "templates/server-ts");
const builderPkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const MARKER = ".mcp-builder.json";
const HEADER = "// Generated by mcp-server-builder from manifest.yaml. Do not edit: change the manifest and regenerate.\n";

export const SDK_VERSION = "^1.30.1";
export const ZOD_VERSION = "^3.25.0";
export const JOSE_VERSION = "^6.1.3";

const lit = (v) => JSON.stringify(v);

// ---------- zod code emission ----------

export function zodForArg(spec, indent = "  ") {
  let code;
  switch (spec.type) {
    case "string":
      code = spec.enum ? `z.enum(${lit(spec.enum.map(String))})` : "z.string()";
      if (!spec.enum && spec.min !== undefined) code += `.min(${spec.min})`;
      if (!spec.enum && spec.max !== undefined) code += `.max(${spec.max})`;
      break;
    case "integer":
    case "number":
      code = spec.type === "integer" ? "z.number().int()" : "z.number()";
      if (spec.min !== undefined) code += `.min(${spec.min})`;
      if (spec.max !== undefined) code += `.max(${spec.max})`;
      if (spec.enum) code = `z.union([${spec.enum.map((v) => `z.literal(${lit(v)})`).join(", ")}])`;
      break;
    case "boolean":
      code = "z.boolean()";
      break;
    case "array": {
      const item = spec.items ? zodObject(spec.items, indent + "  ") : "z.unknown()";
      code = `z.array(${item})`;
      if (spec.min !== undefined) code += `.min(${spec.min})`;
      if (spec.max !== undefined) code += `.max(${spec.max})`;
      break;
    }
    case "object":
      code = spec.items ? zodObject(spec.items, indent + "  ") : "z.record(z.string(), z.unknown())";
      break;
    default:
      throw new Error(`Unsupported argument type "${spec.type}"`);
  }
  if (spec.description) code += `.describe(${lit(spec.description)})`;
  if (spec.default !== undefined) code += `.default(${lit(spec.default)})`;
  else if (!spec.required) code += ".optional()";
  return code;
}

function zodObject(args, indent = "  ") {
  const entries = Object.entries(args ?? {});
  if (entries.length === 0) return "z.object({}).strict()";
  const inner = entries.map(([k, s]) => `${indent}  ${lit(k)}: ${zodForArg(s, indent + "  ")},`).join("\n");
  return `z.object({\n${inner}\n${indent}}).strict()`;
}

function zodRecord(fields) {
  if (!fields) return "z.object({}).catchall(z.unknown())";
  return `z.object({ ${Object.keys(fields).map((k) => `${lit(k)}: z.unknown()`).join(", ")} })`;
}

function zodResult(response, fields) {
  const rec = zodRecord(fields);
  return response.itemsPath ? `z.object({ items: z.array(${rec}), nextCursor: z.string().optional() })` : rec;
}

export function zodOutput(shape, response, fields) {
  const result = zodResult(response, fields);
  if (shape === "list" || shape === "record") return result;
  if (shape === "job") return `z.object({ jobId: z.string().nullable(), state: z.string(), result: ${result} })`;
  return `z.object({
    status: z.enum(["preview", "done"]),
    message: z.string().optional(),
    preview: z.object({ method: z.string(), path: z.string(), query: z.record(z.string(), z.string()).optional(), body: z.unknown().optional() }).optional(),
    result: ${result}.optional(),
  })`;
}

// ---------- normalization ----------

const responseBinding = (response, mappings) => {
  const r = response ?? {};
  const mapping = r.mapping ?? "raw";
  const out = { ...r };
  delete out.mapping;
  if (mapping !== "raw") out.fields = mappings[mapping];
  return out;
};

export function normalize(manifest) {
  const mappings = manifest.mappings ?? {};
  const tools = allTools(manifest)
    .filter((t) => t.enabled !== false)
    .map((t) => {
      const std = catalog[t.name];
      const kind = t.kind;
      const args = structuredClone(t.args ?? {});
      const requireConfirmation = kind !== "read" && t.requireConfirmation !== false;
      if (requireConfirmation && !args.confirm) {
        args.confirm = { type: "boolean", default: false, description: "Set true only after the user approved the preview." };
      }
      if (!requireConfirmation) delete args.confirm;
      let description = t.description ?? std?.description;
      if (t.deprecated) description = `Deprecated: ${t.replacedBy ? `use ${t.replacedBy} instead. ` : "will be removed in the next major version. "}${description}`;
      const response = responseBinding({ ...t.response, mapping: t.mapping }, mappings);
      const shape = t.longRunning ? "job" : kind !== "read" ? "write" : response.itemsPath ? "list" : "record";
      return {
        name: t.name,
        title: t.title ?? std?.title ?? t.name,
        description,
        kind,
        scope: t.scope,
        idempotent: t.idempotent === true,
        requireConfirmation,
        maxTotal: t.maxTotal,
        deprecated: t.deprecated === true,
        replacedBy: t.replacedBy,
        request: t.request,
        response,
        longRunning: t.longRunning ? { pollIntervalMs: 2000, timeoutMs: 300000, ...t.longRunning } : undefined,
        shape,
        args,
      };
    });

  const resources = (manifest.resources ?? []).map((r) => ({
    name: r.name,
    title: r.title,
    description: r.description,
    uri: r.uri,
    mimeType: r.mimeType ?? (r.file ? guessMime(r.file) : "application/json"),
    scope: r.scope,
    file: r.file,
    request: r.request,
    response: r.request ? responseBinding(r.response, mappings) : undefined,
    list: r.list,
    listResponse: r.list ? responseBinding(r.listResponse ?? { itemsPath: "" }, mappings) : undefined,
  }));

  const prompts = (manifest.prompts ?? []).map((p) => ({
    name: p.name,
    title: p.title,
    description: p.description,
    scope: p.scope,
    args: Object.fromEntries(Object.entries(p.args ?? {}).map(([k, a]) => [k, { description: a.description, required: a.required === true, completeFrom: a.completeFrom }])),
    template: p.template,
    embedResources: p.embedResources ?? [],
  }));

  const readScopes = [...new Set(tools.filter((t) => t.kind === "read" && t.scope).map((t) => t.scope))];
  const access = manifest.access ?? {};
  const audit = manifest.audit ?? {};
  const server = manifest.server;
  const config = {
    company: { name: manifest.company.name, defaultCurrency: manifest.company.defaultCurrency ?? "USD" },
    server: {
      name: server.name,
      version: server.version,
      instructions: server.instructions,
      transports: server.transports ?? ["stdio"],
      http: { port: server.http?.port ?? 3000, path: server.http?.path ?? "/mcp", publicUrl: server.http?.publicUrl },
    },
    api: { baseUrl: manifest.api.baseUrl, timeoutMs: manifest.api.timeoutMs ?? 10000, headers: manifest.api.headers ?? {}, auth: manifest.api.auth, rateLimit: manifest.api.rateLimit },
    access: {
      stdioScopes: access.stdioScopes ?? readScopes,
      apiKeys: (access.apiKeys ?? []).map((k) => ({ clientId: k.clientId, keyHashEnv: k.keyHashEnv, scopes: k.scopes, context: k.context ?? {}, rateLimit: k.rateLimit })),
      oauth: access.oauth ? { scopeClaim: "scope", contextClaims: {}, ...access.oauth } : undefined,
    },
    audit: { enabled: audit.enabled ?? true, sink: audit.sink ?? "stderr", path: audit.path, url: audit.url, includeArguments: audit.includeArguments ?? true, redactFields: audit.redactFields ?? [] },
  };
  return { config, tools, resources, prompts };
}

function guessMime(file) {
  const ext = path.extname(file).toLowerCase();
  return { ".md": "text/markdown", ".txt": "text/plain", ".json": "application/json", ".html": "text/html", ".csv": "text/csv" }[ext] ?? "application/octet-stream";
}

export function envVars(config) {
  const out = [];
  const a = config.api.auth;
  for (const key of ["valueEnv", "tokenEnv", "usernameEnv", "passwordEnv", "clientIdEnv", "clientSecretEnv"]) {
    if (a[key]) out.push({ name: a[key], note: `Credential for the company API (${a.type}).` });
  }
  for (const k of config.access.apiKeys) out.push({ name: k.keyHashEnv, note: `SHA-256 hash of the API key for client "${k.clientId}" (npm run hash-key).` });
  return out;
}

// ---------- file rendering ----------

const tsName = (name) => name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
const omit = (obj, keys) => Object.fromEntries(Object.entries(obj).filter(([k, v]) => !keys.includes(k) && v !== undefined));

function renderTool(t) {
  const data = omit(t, ["args"]);
  const body = JSON.stringify(data, null, 2).replace(/\n}$/, "");
  return `${HEADER}import { z } from "zod/v4";
import type { ToolDef } from "../runtime/types.js";

export const ${tsName(t.name)}: ToolDef = ${body},
  input: ${zodObject(t.args)},
  output: ${zodOutput(t.shape, t.response, t.response.fields)},
};
`;
}

function renderIndex(kind, type, items) {
  const imports = items.map((i) => `import { ${tsName(i.name)} } from "./${i.name}.js";`).join("\n");
  return `${HEADER}import type { ${type} } from "../runtime/types.js";
${imports}

export const ${kind}: ${type}[] = [${items.map((i) => tsName(i.name)).join(", ")}];
`;
}

const renderData = (type, item) => `${HEADER}import type { ${type} } from "../runtime/types.js";

export const ${tsName(item.name)}: ${type} = ${JSON.stringify(omit(item, []), null, 2)};
`;

function renderIndexTs() {
  return `${HEADER}import { config } from "./config.js";
import { tools } from "./tools/index.js";
import { resources } from "./resources/index.js";
import { prompts } from "./prompts/index.js";
import { createRuntime, start } from "./runtime/runtime.js";

// Load settings from .env when present (real environment variables win).
// Looked up next to the package (not the current folder), so it also works when Claude Desktop starts the server.
try { process.loadEnvFile(new URL("../.env", import.meta.url)); } catch { /* no .env file */ }

start(createRuntime(config, tools, resources, prompts)).catch((err) => {
  process.stderr.write(\`Failed to start: \${err?.stack ?? err}\\n\`);
  process.exit(1);
});
`;
}

function renderReadme(n, env) {
  const { config, tools, resources, prompts } = n;
  const http = config.server.transports.includes("http");
  return `# ${config.server.name}

MCP server for **${config.company.name}**, generated by mcp-server-builder ${builderPkg.version} from \`manifest.yaml\`.
Version ${config.server.version}. Do not edit files in \`src/\` by hand: change \`manifest.yaml\` and regenerate.

## What it exposes

| Tools (${tools.length}) | Resources (${resources.length}) | Prompts (${prompts.length}) |
|---|---|---|
| ${tools.map((t) => t.name + (t.deprecated ? " (deprecated)" : "")).join("<br>")} | ${resources.map((r) => r.name).join("<br>") || "–"} | ${prompts.map((p) => p.name).join("<br>") || "–"} |

## Run it

1. \`npm install\`
2. \`npm run build\`
3. Copy \`.env.example\` to \`.env\` and fill in the values (never commit \`.env\`).
4. Start it:
   - Local (Claude Desktop / Claude Code): \`npm run start:stdio\`
${http ? `   - Remote: \`npm run start:http\`, listening on port ${config.server.http.port} at \`${config.server.http.path}\`. Set \`HOST=0.0.0.0\` to accept outside connections.\n` : ""}
${http ? `## Give a client access (API keys)

1. Run \`npm run hash-key\`. It prints a new key and its SHA-256 hash.
2. Give the **key** to the client. It sends \`Authorization: Bearer <key>\`.
3. Put only the **hash** in the matching \`*_SHA256\` variable in \`.env\`.
` : ""}
## Settings

| Variable | Purpose |
|---|---|
${env.map((e) => `| \`${e.name}\` | ${e.note} |`).join("\n")}
| \`API_BASE_URL\` | Points the server at another API base URL, e.g. staging (default: ${config.api.baseUrl}) |
| \`MCP_TRANSPORT\` | \`stdio\` or \`http\` (default: ${config.server.transports[0]}) |
| \`PORT\`, \`HOST\` | HTTP listen address (default ${config.server.http.port}, 127.0.0.1) |
| \`AUDIT_LOG_PATH\` | Overrides the audit log file path |
| \`MCP_OAUTH_JWKS_URL\` | Overrides where OAuth signing keys are fetched from |
`;
}

function renderEnvExample(env) {
  return [
    "# Copy to .env and fill in. Never commit the real values.",
    ...env.flatMap((e) => [`# ${e.note}`, `${e.name}=`]),
    "",
    "# Optional",
    "# MCP_TRANSPORT=stdio",
    "# PORT=3000",
    "# HOST=127.0.0.1",
    "# AUDIT_LOG_PATH=logs/audit.jsonl",
    "# API_BASE_URL=https://staging-api.example.com",
    "",
  ].join("\n");
}

// ---------- entry point ----------

export class ManifestError extends Error {
  constructor(errors) {
    super(`Manifest is not valid:\n${errors.map((e) => `  - ${e}`).join("\n")}`);
    this.errors = errors;
  }
}

/**
 * Generates the server project into outDir. Refuses to write into a
 * non-empty folder that it did not create, so user files are never overwritten.
 */
export function generate(manifestPath, outDir) {
  const manifestText = readFileSync(manifestPath, "utf8");
  const manifest = YAML.parse(manifestText);
  const baseDir = path.dirname(path.resolve(manifestPath));
  const errors = validateManifest(manifest, { baseDir });
  if (errors.length) throw new ManifestError(errors);

  if (existsSync(outDir) && readdirSync(outDir).length > 0 && !existsSync(path.join(outDir, MARKER))) {
    throw new Error(`${outDir} is not empty and was not created by mcp-builder. Choose an empty folder.`);
  }
  rmSync(path.join(outDir, "src"), { recursive: true, force: true });
  rmSync(path.join(outDir, "assets"), { recursive: true, force: true });

  const n = normalize(manifest);
  const env = envVars(n.config);
  const files = new Map();
  const write = (rel, text) => files.set(rel, text);

  write("src/config.ts", `${HEADER}import type { ServerConfig } from "./runtime/types.js";\n\nexport const config: ServerConfig = ${JSON.stringify(n.config, null, 2)};\n`);
  for (const t of n.tools) write(`src/tools/${t.name}.ts`, renderTool(t));
  write("src/tools/index.ts", renderIndex("tools", "ToolDef", n.tools));
  for (const r of n.resources) write(`src/resources/${r.name}.ts`, renderData("ResourceDef", r));
  write("src/resources/index.ts", renderIndex("resources", "ResourceDef", n.resources));
  for (const p of n.prompts) write(`src/prompts/${p.name}.ts`, renderData("PromptDef", p));
  write("src/prompts/index.ts", renderIndex("prompts", "PromptDef", n.prompts));
  write("src/index.ts", renderIndexTs());

  const http = n.config.server.transports.includes("http");
  write("package.json", JSON.stringify({
    name: n.config.server.name,
    version: n.config.server.version,
    description: manifest.server.description ?? `MCP server for ${n.config.company.name}`,
    type: "module",
    private: true,
    bin: { [n.config.server.name]: "dist/index.js" },
    engines: { node: ">=20.12" },
    scripts: {
      build: "tsc",
      start: "node dist/index.js",
      "start:stdio": "node dist/index.js --stdio",
      ...(http ? { "start:http": "node dist/index.js --http" } : {}),
      "hash-key": "node scripts/hash-key.mjs",
    },
    dependencies: { "@modelcontextprotocol/sdk": SDK_VERSION, zod: ZOD_VERSION, jose: JOSE_VERSION },
    devDependencies: { typescript: "^5.6.0", "@types/node": "^22.0.0" },
  }, null, 2) + "\n");
  write(".env.example", renderEnvExample(env));
  write(".gitignore", "node_modules/\ndist/\n.env\nlogs/\n");
  write("README.md", renderReadme(n, env));
  write("manifest.yaml", manifestText);
  write(MARKER, JSON.stringify({ builder: builderPkg.version, manifestSha256: createHash("sha256").update(manifestText).digest("hex"), serverVersion: n.config.server.version }, null, 2) + "\n");

  for (const [rel, text] of files) {
    const dest = path.join(outDir, rel);
    mkdirSync(path.dirname(dest), { recursive: true });
    writeFileSync(dest, text);
  }
  cpSync(path.join(templateDir, "src/runtime"), path.join(outDir, "src/runtime"), { recursive: true });
  cpSync(path.join(templateDir, "tsconfig.json"), path.join(outDir, "tsconfig.json"));
  cpSync(path.join(templateDir, "scripts"), path.join(outDir, "scripts"), { recursive: true });
  for (const r of n.resources.filter((r) => r.file)) {
    const dest = path.join(outDir, "assets", r.file);
    mkdirSync(path.dirname(dest), { recursive: true });
    cpSync(path.resolve(baseDir, r.file), dest);
  }
  const warnings = n.tools.filter((t) => t.maxTotal !== undefined).map((t) => `${t.name}: maxTotal is not enforced yet by the generated server; keep this tool disabled or rely on the company API's own limits`);
  return { outDir, ...n, files: [...files.keys()], warnings };
}
